local set = vim.keymap.set
set('n', '<space>xf', '<cmd>source %<CR>', { desc = 'Source this buffer' })
set('n', '<space>xx', ':.lua<CR>', { desc = 'Lua: source this line' })
set('v', '<space>x', ':lua<CR>', { desc = 'Lua: source this selection' })
set("n", "-", "<cmd>Oil<CR>", { desc = 'Oil' })
set('n', '<Esc>', '<cmd>nohlsearch<CR>', { desc = 'Clear highlight search' })
set('n', '<M-(>', '<c-w>5<', { desc = 'Decrease current window width' })
set('n', '<M-)>', '<c-w>5>', { desc = 'Increase current window width' })
set('n', '<M-+>', '<c-w>+', { desc = 'Increase current window height' })
set('n', '<M-_>', '<c-w>-', { desc = 'Decrease current window height' })
set('n', '<leader>ld', vim.diagnostic.setloclist, { desc = 'Open [d]iagnostic location list' })
set("x", "<leader>p", [["_dP]], { desc = 'Replace selected, mantain register' })
set({ 'n', 'v' }, "<leader>d", [["_d]], { desc = 'Delete selected, mantain register' })
set('n', "<leader>s", ":%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>", { desc = "Rename all inside <>" })
set("n", "<leader>cn", "<cmd>cnext<CR>zz", { desc = 'Next quickfix list entry' })
set("n", "<leader>cp", "<cmd>cprev<CR>zz", { desc = 'Previous quickfix list entry' })
set("n", "<leader>ln", "<cmd>lnext<CR>zz", { desc = 'Next location list' })
set("n", "<leader>lp", "<cmd>lprev<CR>zz", { desc = 'Previous location list' })
set("i", "<C-U>", "<nop>", { desc = 'To avoid when C-Y' })
set('', '<F1>', '<Nop>', { noremap = true, silent = true })
set({ 'n', 'v', 'i' }, "<C-C>", "<CMD>cclose<CR>", { desc = "Close quickfix" })
set("n", "<leader>cf", ":let @+ = expand('%:p')<CR>", { desc = 'Copy full path curren file to os register' })
