import = ["/Users/dan/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true
"window.dynamic_title" = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "Regular Italic"

[font.normal]
family = "MonoLisa"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u000B"
key = "K"
mods = "Command"

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
program = "sh"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/usr/local/bin/zsh"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
